# Generated by Django 2.0.3 on 2018-03-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('codproc', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('serventia', models.CharField(max_length=60)),
                ('comarca', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Process')),
            ],
        ),
    ]
