# Generated by Django 2.0.3 on 2018-03-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_auto_20180327_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('cod', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('serventia', models.CharField(max_length=40)),
                ('comarca', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Process')),
            ],
        ),
    ]
