# Generated by Django 2.0.3 on 2018-04-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_process_processfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
        migrations.CreateModel(
            name='ProcessCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('character_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Character')),
                ('process_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Process')),
            ],
            options={
                'verbose_name': 'processcharacter',
                'verbose_name_plural': 'processcharacters',
            },
        ),
        migrations.AlterModelOptions(
            name='processfile',
            options={'verbose_name': 'processfile', 'verbose_name_plural': 'processfiles'},
        ),
    ]
