# Generated by Django 2.0.3 on 2018-03-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_process_processfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processfile',
            options={'verbose_name': 'processfile', 'verbose_name_plural': 'processfiles'},
        ),
    ]
