# Generated by Django 2.0.3 on 2018-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180417_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcharacter',
            name='type',
        ),
        migrations.AddField(
            model_name='processcharacter',
            name='typerel',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
